### ISSUE TITLE
Make possible to handle the error only

### ISSUE THREAD

**Issue by YankoDiev-PrimeHolding** [Prime-Holding/RxBloc#22]
Currently, we can use `setResultStateHandler()` only which handles both the isLoading and error state. However, we may want some time to handle just the error

**Comment by DDavidPrime** [comment]
Is there a case where you don't want to use the `setResultStateHandler()` for isLoading ? Why don't you use it anyway and ignore the isLoading state? If not, can you give an short example where this would be useful?

**Comment by YankoDiev-PrimeHolding** [comment]
Hi @DDavidPrime, it is shame on me as a person who learns from examples only to not give one. Here it is...
For the chat implementation, I got a use case where I need to show a loading spin just the first time (when the chat initiates for the first time). Then for any further update (send/receive a message, message status change), I do refresh again but this time I don't want to bother the loading state.
However, I've implemented a [temporary solution](https://gitlab.programista.pro/codebase/flutter/flutter-package-chat-voip/-/blob/develop/packages/prime_chat/lib/src/base/extensions/chat_room_bloc_extensions.dart) in the project. So I can easily use it [in the bloc](https://gitlab.programista.pro/codebase/flutter/flutter-package-chat-voip/-/blob/develop/packages/prime_chat/lib/src/feature_chat_room/blocs/chat_room_bloc.dart#L86).

Please let me know if you have further questions.
