### ISSUE TITLE
Organizing a library packages

### ISSUE THREAD

**Issue by YankoDiev-PrimeHolding** [Prime-Holding/RxBloc#24]
We've noticed that the best way to organize a package is by following the rule explained [here](https://dart.dev/guides/libraries/create-library-packages#organizing-a-library-package).

For instance, we should have all of our libraries in our [/lib](https://github.com/ReactiveX/rxdart/tree/master/lib) directory where all of our lib files will be placed. Then a [/src](https://github.com/ReactiveX/rxdart/tree/master/lib/src) directory inside it containing the libraries grouped by their own folders. 
That way we can easily [export](https://raw.githubusercontent.com/ReactiveX/rxdart/master/lib/rxdart.dart) all files we need and then wherever we need this library we can have it using just 1 import row.
![Screenshot 2020-07-24 at 09 36 12](https://user-images.githubusercontent.com/62933904/88366179-213fc200-cd91-11ea-9a0d-c83e26f5be18.png)

**Comment by DDavidPrime** [comment]
Although I agree with you, we need to take into consideration that this may be a breaking change for projects using the current version of the package.
